from typing import Literal

from pydantic import BaseModel, Field


class EligibilityFlag(BaseModel):
    severity: Literal["blocking", "warning", "info"] = Field(
        description="blocking = case cannot proceed without resolving this; "
                    "warning = should be resolved before filing; info = attorney FYI"
    )
    category: Literal["missing_document", "timeline_conflict", "eligibility_gap", "data_inconsistency"]
    message: str = Field(description="Plain-language explanation an attorney can act on immediately")
    related_document_type: str | None = Field(
        default=None, description="Which document type this flag concerns, if any"
    )


class EligibilitySummary(BaseModel):
    """
    The core deliverable: what the agent hands the attorney after reviewing
    every document in the case against the visa category's requirements.
    This is deliberately NOT a legal opinion — it's a triage summary that
    cuts the attorney's manual document review time down, with every claim
    traceable to a specific uploaded document.
    """
    visa_category: str
    documents_reviewed: int
    overall_readiness: Literal["ready_to_file", "needs_attention", "not_ready"]

    flags: list[EligibilityFlag] = Field(default_factory=list)

    timeline_narrative: str = Field(
        description="Chronological narrative built from extracted dates across all documents "
                    "(entry dates, status changes, employment start dates, etc.)"
    )
    missing_document_types: list[str] = Field(
        default_factory=list,
        description="Document types the visa category requires that have not been uploaded yet",
    )
    attorney_notes: str = Field(
        description="2-4 sentence summary for the attorney - not legal advice, a triage briefing"
    )

    disclaimer: str = (
        "This summary is generated by an AI assistant to accelerate document review. "
        "It is not legal advice and must be verified by a licensed attorney before filing."
    )


class CaseCreate(BaseModel):
    client_name: str
    client_email: str | None = None
    visa_category: str


class CaseSummaryResponse(BaseModel):
    id: str
    client_id: str
    visa_category: str
    status: str
    eligibility_summary: EligibilitySummary | None = None

    class Config:
        from_attributes = True
